// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UAP.CourseCatalog.Infrastructure.Data;

#nullable disable

namespace UAP.CourseCatalog.Infrastructure.Data.Migrations
{
    [DbContext(typeof(CourseCatalogDbContext))]
    partial class CourseCatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UAP.CourseCatalog.Domain.Entities.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<Guid>("CoordinatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<int>("CurrentEnrollment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsBorrowable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("OfferingSemester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorId")
                        .HasDatabaseName("IX_Courses_CoordinatorId");

                    b.HasIndex("CourseCode")
                        .IsUnique()
                        .HasDatabaseName("IX_Courses_CourseCode");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Courses_DepartmentId");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Courses_IsActive");

                    b.HasIndex("IsActive", "IsBorrowable")
                        .HasDatabaseName("IX_Courses_Active_Borrowable");

                    b.HasIndex("OfferingSemester", "AcademicYear")
                        .HasDatabaseName("IX_Courses_Semester_Year");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            AcademicYear = 2025,
                            CoordinatorId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CourseCode = "CS101",
                            CreatedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9566),
                            Credits = 3,
                            CurrentEnrollment = 0,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Fundamental concepts of programming and problem solving",
                            IsActive = true,
                            IsBorrowable = true,
                            MaxCapacity = 50,
                            ModifiedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9566),
                            OfferingSemester = "Fall",
                            Title = "Introduction to Programming"
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AcademicYear = 2025,
                            CoordinatorId = new Guid("44444444-4444-4444-4444-444444444444"),
                            CourseCode = "CS201",
                            CreatedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9571),
                            Credits = 4,
                            CurrentEnrollment = 0,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Study of fundamental data structures and algorithm analysis",
                            IsActive = true,
                            IsBorrowable = true,
                            MaxCapacity = 40,
                            ModifiedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9571),
                            OfferingSemester = "Spring",
                            Title = "Data Structures and Algorithms"
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            AcademicYear = 2025,
                            CoordinatorId = new Guid("55555555-5555-5555-5555-555555555555"),
                            CourseCode = "MATH101",
                            CreatedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9574),
                            Credits = 4,
                            CurrentEnrollment = 0,
                            DepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Differential and integral calculus of single variable functions",
                            IsActive = true,
                            IsBorrowable = true,
                            MaxCapacity = 60,
                            ModifiedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9574),
                            OfferingSemester = "Fall",
                            Title = "Calculus I"
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AcademicYear = 2025,
                            CoordinatorId = new Guid("66666666-6666-6666-6666-666666666666"),
                            CourseCode = "PHYS101",
                            CreatedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9577),
                            Credits = 4,
                            CurrentEnrollment = 0,
                            DepartmentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            Description = "Mechanics, heat, and sound",
                            IsActive = true,
                            IsBorrowable = false,
                            MaxCapacity = 55,
                            ModifiedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9577),
                            OfferingSemester = "Fall",
                            Title = "General Physics I"
                        });
                });

            modelBuilder.Entity("UAP.CourseCatalog.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("HeadOfDepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("IX_Departments_Code");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Departments_IsActive");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Code = "CS",
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9147),
                            Description = "Computer Science Department",
                            HeadOfDepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            ModifiedBy = "system",
                            ModifiedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9151),
                            Name = "Computer Science Department"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Code = "MATH",
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9182),
                            Description = "Mathematics Department",
                            HeadOfDepartmentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            IsActive = true,
                            ModifiedBy = "system",
                            ModifiedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9183),
                            Name = "Mathematics Department"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Code = "PHYS",
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9191),
                            Description = "Physics Department",
                            HeadOfDepartmentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            IsActive = true,
                            ModifiedBy = "system",
                            ModifiedOn = new DateTime(2025, 12, 5, 13, 35, 34, 241, DateTimeKind.Utc).AddTicks(9192),
                            Name = "Physics Department"
                        });
                });

            modelBuilder.Entity("UAP.CourseCatalog.Domain.Entities.Prerequisite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PrerequisiteCourseId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrerequisiteCourseId");

                    b.HasIndex("CourseId", "PrerequisiteCourseId")
                        .IsUnique()
                        .HasDatabaseName("IX_Prerequisites_Course_Prerequisite");

                    b.ToTable("Prerequisites");

                    b.HasData(
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            PrerequisiteCourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("UAP.CourseCatalog.Domain.Entities.Course", b =>
                {
                    b.HasOne("UAP.CourseCatalog.Domain.Entities.Department", "Department")
                        .WithMany("Courses")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("UAP.CourseCatalog.Domain.Entities.Prerequisite", b =>
                {
                    b.HasOne("UAP.CourseCatalog.Domain.Entities.Course", "Course")
                        .WithMany("Prerequisites")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UAP.CourseCatalog.Domain.Entities.Course", "PrerequisiteCourse")
                        .WithMany()
                        .HasForeignKey("PrerequisiteCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("PrerequisiteCourse");
                });

            modelBuilder.Entity("UAP.CourseCatalog.Domain.Entities.Course", b =>
                {
                    b.Navigation("Prerequisites");
                });

            modelBuilder.Entity("UAP.CourseCatalog.Domain.Entities.Department", b =>
                {
                    b.Navigation("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
