// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UAP.StudentAcademic.Infrastructure.Data;

#nullable disable

namespace UAP.StudentAcademic.Infrastructure.Migrations
{
    [DbContext(typeof(StudentAcademicDbContext))]
    partial class StudentAcademicDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UAP.StudentAcademic.Domain.Entities.AcademicSemester", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<int>("CompletedCredits")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegisteredCredits")
                        .HasColumnType("int");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("SemesterGPA")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("IsCompleted")
                        .HasDatabaseName("IX_AcademicSemesters_IsCompleted");

                    b.HasIndex("IsCurrent")
                        .HasDatabaseName("IX_AcademicSemesters_IsCurrent");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_AcademicSemesters_StudentId");

                    b.HasIndex("StudentId", "Semester", "AcademicYear")
                        .IsUnique()
                        .HasDatabaseName("IX_AcademicSemesters_Student_Semester_Year");

                    b.ToTable("AcademicSemesters");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            AcademicYear = 2023,
                            CompletedCredits = 15,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(919),
                            EndDate = new DateTime(2023, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = true,
                            IsCurrent = false,
                            ModifiedBy = "system",
                            ModifiedOn = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(921),
                            RegisteredCredits = 15,
                            Semester = "Fall",
                            SemesterGPA = 3.8m,
                            StartDate = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            AcademicYear = 2024,
                            CompletedCredits = 0,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(934),
                            EndDate = new DateTime(2024, 5, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCompleted = false,
                            IsCurrent = true,
                            ModifiedBy = "system",
                            ModifiedOn = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(934),
                            RegisteredCredits = 15,
                            Semester = "Spring",
                            SemesterGPA = 0.0m,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa")
                        });
                });

            modelBuilder.Entity("UAP.StudentAcademic.Domain.Entities.CourseGrade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<string>("CourseCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CourseTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("GradeDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinal")
                        .HasColumnType("bit");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubmittedById")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("IX_CourseGrades_CourseId");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_CourseGrades_StudentId");

                    b.HasIndex("Semester", "AcademicYear")
                        .HasDatabaseName("IX_CourseGrades_Semester_Year");

                    b.HasIndex("StudentId", "CourseId", "Semester", "AcademicYear")
                        .IsUnique()
                        .HasDatabaseName("IX_CourseGrades_Student_Course_Semester_Year");

                    b.ToTable("CourseGrades");

                    b.HasData(
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            AcademicYear = 2023,
                            CourseCode = "CS101",
                            CourseId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CourseTitle = "Introduction to Programming",
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(1004),
                            Credits = 3,
                            Grade = "A",
                            GradeDate = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(1003),
                            IsFinal = true,
                            ModifiedBy = "system",
                            ModifiedOn = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(1006),
                            Remarks = "Excellent performance",
                            Semester = "Fall",
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            SubmittedById = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            AcademicYear = 2023,
                            CourseCode = "MATH101",
                            CourseId = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CourseTitle = "Calculus I",
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(1014),
                            Credits = 4,
                            Grade = "BPlus",
                            GradeDate = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(1014),
                            IsFinal = true,
                            ModifiedBy = "system",
                            ModifiedOn = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(1015),
                            Remarks = "Good work",
                            Semester = "Fall",
                            StudentId = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            SubmittedById = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("UAP.StudentAcademic.Domain.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CompletedCredits")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("CumulativeCredits")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("CurrentCGPA")
                        .HasPrecision(3, 2)
                        .HasColumnType("decimal(3,2)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpectedGraduationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ModifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CurrentCGPA")
                        .HasDatabaseName("IX_Students_CurrentCGPA");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("IX_Students_DepartmentId");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Students_Status");

                    b.HasIndex("StudentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Students_StudentNumber");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("IX_Students_UserId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CompletedCredits = 45m,
                            CreatedBy = "system",
                            CreatedOn = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(117),
                            CumulativeCredits = 45m,
                            CurrentCGPA = 3.75m,
                            DepartmentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            EnrollmentDate = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ExpectedGraduationDate = new DateTime(2028, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ModifiedBy = "system",
                            ModifiedOn = new DateTime(2025, 12, 11, 9, 44, 59, 422, DateTimeKind.Utc).AddTicks(122),
                            Program = "Computer Science",
                            Status = "Active",
                            StudentNumber = "240120-1234",
                            UserId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("UAP.StudentAcademic.Domain.Entities.AcademicSemester", b =>
                {
                    b.HasOne("UAP.StudentAcademic.Domain.Entities.Student", "Student")
                        .WithMany("AcademicSemesters")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UAP.StudentAcademic.Domain.Entities.CourseGrade", b =>
                {
                    b.HasOne("UAP.StudentAcademic.Domain.Entities.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("UAP.StudentAcademic.Domain.Entities.Student", b =>
                {
                    b.Navigation("AcademicSemesters");

                    b.Navigation("Grades");
                });
#pragma warning restore 612, 618
        }
    }
}
