// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UAP.Authentication.Infrastructure.Data;

#nullable disable

namespace UAP.Authentication.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AuthenticationDbContext))]
    partial class AuthenticationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UAP.Authentication.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("NormalizedName")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("45b600de-7645-4d22-a4c2-f66dd2288b80"),
                            Description = "Student role",
                            IsSystemRole = true,
                            Name = "Student",
                            NormalizedName = "STUDENT"
                        },
                        new
                        {
                            Id = new Guid("9754b032-22a8-45bc-ac0a-b0f36997f904"),
                            Description = "Staff role",
                            IsSystemRole = true,
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        },
                        new
                        {
                            Id = new Guid("617cd4ef-b4cd-46bf-9197-90984aff3cf8"),
                            Description = "Administrator role",
                            IsSystemRole = true,
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = new Guid("8d10ac8e-31df-4ab7-9882-7d7cb2dcffe9"),
                            Description = "Course Coordinator role",
                            IsSystemRole = true,
                            Name = "CourseCoordinator",
                            NormalizedName = "COURSECOORDINATOR"
                        });
                });

            modelBuilder.Entity("UAP.Authentication.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId", "Permission")
                        .IsUnique();

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4547d871-4f4e-4841-83dc-ec9f3c9bbbba"),
                            Permission = "course.view",
                            RoleId = new Guid("45b600de-7645-4d22-a4c2-f66dd2288b80")
                        },
                        new
                        {
                            Id = new Guid("21afe720-6db6-43b9-993a-fe2506a7499e"),
                            Permission = "course.register",
                            RoleId = new Guid("45b600de-7645-4d22-a4c2-f66dd2288b80")
                        },
                        new
                        {
                            Id = new Guid("e3dd6ae7-76bd-4854-9688-321b1ab231cf"),
                            Permission = "grade.view",
                            RoleId = new Guid("45b600de-7645-4d22-a4c2-f66dd2288b80")
                        },
                        new
                        {
                            Id = new Guid("81d3908b-5bd5-4e19-9767-025f15cc70b1"),
                            Permission = "profile.view",
                            RoleId = new Guid("45b600de-7645-4d22-a4c2-f66dd2288b80")
                        },
                        new
                        {
                            Id = new Guid("5cbe3144-056c-4d11-bcff-a4726189281c"),
                            Permission = "course.view",
                            RoleId = new Guid("9754b032-22a8-45bc-ac0a-b0f36997f904")
                        },
                        new
                        {
                            Id = new Guid("94a2e913-0046-4105-889a-cd37f420e44c"),
                            Permission = "course.manage",
                            RoleId = new Guid("9754b032-22a8-45bc-ac0a-b0f36997f904")
                        },
                        new
                        {
                            Id = new Guid("8442bd0b-8344-4f87-b727-454fdcfcd8d4"),
                            Permission = "student.view",
                            RoleId = new Guid("9754b032-22a8-45bc-ac0a-b0f36997f904")
                        },
                        new
                        {
                            Id = new Guid("c8413f1f-356f-4b05-b2c3-39693a656783"),
                            Permission = "profile.view",
                            RoleId = new Guid("9754b032-22a8-45bc-ac0a-b0f36997f904")
                        },
                        new
                        {
                            Id = new Guid("a250ed42-34c6-4a15-bcab-4cd0da63c42b"),
                            Permission = "*",
                            RoleId = new Guid("617cd4ef-b4cd-46bf-9197-90984aff3cf8")
                        },
                        new
                        {
                            Id = new Guid("be8d3567-ffef-446d-a396-6d2634ac19be"),
                            Permission = "course.view",
                            RoleId = new Guid("8d10ac8e-31df-4ab7-9882-7d7cb2dcffe9")
                        },
                        new
                        {
                            Id = new Guid("2261576e-ddbe-4361-9120-126be084290c"),
                            Permission = "course.manage",
                            RoleId = new Guid("8d10ac8e-31df-4ab7-9882-7d7cb2dcffe9")
                        },
                        new
                        {
                            Id = new Guid("06b29514-3660-4dd1-afc0-d319ef36794d"),
                            Permission = "course.coordinate",
                            RoleId = new Guid("8d10ac8e-31df-4ab7-9882-7d7cb2dcffe9")
                        },
                        new
                        {
                            Id = new Guid("69efc93e-d9b7-4787-a969-5b12fe034254"),
                            Permission = "student.view",
                            RoleId = new Guid("8d10ac8e-31df-4ab7-9882-7d7cb2dcffe9")
                        },
                        new
                        {
                            Id = new Guid("aade5b21-c1a9-4d61-a86d-bbcd2e4cb575"),
                            Permission = "grade.manage",
                            RoleId = new Guid("8d10ac8e-31df-4ab7-9882-7d7cb2dcffe9")
                        },
                        new
                        {
                            Id = new Guid("a422de99-bbf8-4053-b223-cbc4f455c5f2"),
                            Permission = "profile.view",
                            RoleId = new Guid("8d10ac8e-31df-4ab7-9882-7d7cb2dcffe9")
                        });
                });

            modelBuilder.Entity("UAP.Authentication.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IsActive");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique();

                    b.HasIndex("UserType");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UAP.Authentication.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("UAP.Authentication.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("UAP.Authentication.Domain.Entities.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("UAP.Authentication.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("UAP.Authentication.Domain.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UAP.Authentication.Domain.Entities.User", "User")
                        .WithMany("Roles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("UAP.Authentication.Domain.Entities.Role", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("UAP.Authentication.Domain.Entities.User", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
